<a href="https://colab.research.google.com/github/maikahayate2006/Projet-final-Java/blob/main/Copie_de_Untitled2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
import pandas as pd

data_path = "/content/logements_iteam_preprocessing_eda.csv"
df = pd.read_csv(data_path)
df.head()

,ID_Logement,Surface_m2,Nb_Pieces,Anciennete_ans,Distance_Centre_km,Quartier,Etat_Logement,Parking,Etage,Classe_Energie,Terrasse,Prix_DT
0,LG-0001,226.0,8,19.0,20.8,Périphérie,NaN,Oui,3,D,Non,575000
1,LG-0002,75.0,1,11.0,21.6,Centre,Bon,Oui,7,D,Non,212000
2,LG-0003,40.0,1,51.0,13.3,Centre,Neuf,Non,4,B,Oui,267000
3,LG-0004,178.0,4,40.0,1.6,Résidentiel,Neuf,Oui,1,E,Oui,620000
4,LG-0005,117.0,3,46.0,16.1,Résidentiel,Bon,Non,5,C,Oui,308000

In [ ]:
print("Dimensions :",df.shape)
print(df.columns.tolist())

Dimensions : (850, 12)
['ID_Logement', 'Surface_m2', 'Nb_Pieces', 'Anciennete_ans', 'Distance_Centre_km', 'Quartier', 'Etat_Logement', 'Parking', 'Etage', 'Classe_Energie', 'Terrasse', 'Prix_DT']

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 850 entries, 0 to 849
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   ID_Logement         850 non-null    object
 1   Surface_m2          824 non-null    float64
 2   Nb_Pieces           850 non-null    int64
 3   Anciennete_ans      829 non-null    float64
 4   Distance_Centre_km  808 non-null    float64
 5   Quartier            850 non-null    object
 6   Etat_Logement       816 non-null    object
 7   Parking             850 non-null    object
 8   Etage               850 non-null    int64
 9   Classe_Energie      820 non-null    object
 10  Terrasse            850 non-null    object
 11  Prix_DT             850 non-null    int64
dtypes: float64(3), int64(3), object(6)
memory usage: 79.8+ KB

In [ ]:
df.describe(include="all").T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
ID_Logement,850,850,LG-0850,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Surface_m2,824.0,NaN,NaN,NaN,145.525485,63.843325,35.0,93.0,142.0,200.25,259.0
Nb_Pieces,850.0,NaN,NaN,NaN,3.943529,1.913713,1.0,2.0,4.0,6.0,9.0
Anciennete_ans,829.0,NaN,NaN,NaN,24.84801,15.333209,0.0,12.0,24.0,38.0,51.0
Distance_Centre_km,808.0,NaN,NaN,NaN,13.964356,7.96961,0.3,7.1,13.65,20.7,28.0
Quartier,850,4,Résidentiel,334,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Etat_Logement,816,3,Bon,405,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Parking,850,2,Oui,458,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Etage,850.0,NaN,NaN,NaN,4.197647,2.578062,0.0,2.0,4.0,6.0,8.0
Classe_Energie,820,5,C,267,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Terrasse,850,2,Non,526,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Prix_DT,850.0,NaN,NaN,NaN,427374.117647,181462.047581,65000.0,293000.0,410000.0,560000.0,1134000.0

In [ ]:
numeric_cols = df.select_dtypes(include=np.number).columns.tolist()
categorical_cols = df.select_dtypes(exclude=np.number).columns.tolist()
print("Variables numériques :", numeric_cols)
print("Variables catégorielles :", categorical_cols)

Variables numériques : ['Surface_m2', 'Nb_Pieces', 'Anciennete_ans', 'Distance_Centre_km', 'Etage', 'Prix_DT']
Variables catégorielles : ['ID_Logement', 'Quartier', 'Etat_Logement', 'Parking', 'Classe_Energie', 'Terrasse']

In [ ]:
(df.isna().mean() * 100).round(2)

ID_Logement           0.00
Surface_m2            3.06
Nb_Pieces             0.00
Anciennete_ans        2.47
Distance_Centre_km    4.94
Quartier              0.00
Etat_Logement         4.00
Parking               0.00
Etage                 0.00
Classe_Energie        3.53
Terrasse              0.00
Prix_DT               0.00
dtype: float64

In [ ]:
for col in ['Quartier', 'Etat_Logement', 'Parking',
            'Classe_Energie', 'Terrasse']:
    print(f"\n--- {col} ---")
    print(df[col].value_counts(dropna=False))

--- Quartier ---
Quartier
Résidentiel    334
Périphérie     223
Centre         177
Côtier         116
Name: count, dtype: int64

--- Etat_Logement ---
Etat_Logement
Bon          405
Neuf         232
À rénover    179
NaN           34
Name: count, dtype: int64

--- Parking ---
Parking
Oui    458
Non    392
Name: count, dtype: int64

--- Classe_Energie ---
Classe_Energie
C      267
D      207
B      172
A       91
E       83
NaN     30
Name: count, dtype: int64

--- Terrasse ---
Terrasse
Non    526
Oui    324
Name: count, dtype: int64

In [ ]:
for col in numeric_cols:
    print(f"\n--- {col} ---")
    print(df[col].value_counts(dropna=False))

--- Surface_m2 ---
Surface_m2
NaN      26
117.0     9
241.0     9
141.0     9
52.0      8
         ..
195.0     1
91.0      1
177.0     1
222.0     1
143.0     1
Name: count, Length: 221, dtype: int64

--- Nb_Pieces ---
Nb_Pieces
3    150
4    133
6    130
5    127
2    122
1    104
7     66
8     17
9      1
Name: count, dtype: int64

--- Anciennete_ans ---
Anciennete_ans
45.0    27
16.0    25
37.0    24
11.0    22
2.0     22
1.0     22
NaN     21
24.0    21
4.0     20
21.0    20
0.0     20
34.0    20
48.0    19
14.0    19
42.0    19
12.0    19
13.0    18
33.0    18
31.0    17
9.0     17
23.0    17
35.0    17
30.0    16
47.0    16
32.0    16
46.0    16
51.0    16
5.0     16
49.0    15
17.0    15
15.0    14
44.0    14
10.0    14
3.0     14
8.0     14
6.0     14
20.0    14
22.0    14
40.0    13
18.0    13
26.0    13
41.0    13
19.0    12
36.0    12
50.0    12
43.0    11
25.0    11
27.0    11
29.0    11
39.0    10
28.0    10
7.0      9
38.0     7
Name: count, dtype: int64

--- Distance_Centre_km ---
Distance_Centre_km
NaN     42
11.0     8
4.8      7
14.3     7
1.0      6
        ..
10.3     1
15.9     1
19.2     1
15.7     1
2.7      1
Name: count, Length: 269, dtype: int64

--- Etage ---
Etage
8    113
6    102
4    102
5     97
2     93
7     90
3     89
0     88
1     76
Name: count, dtype: int64

--- Prix_DT ---
Prix_DT
298000    8
367000    5
458000    5
316000    5
296000    5
         ..
369000    1
335000    1
612000    1
428000    1
644000    1
Name: count, Length: 491, dtype: int64

In [ ]:
df_clean = df.copy()

In [ ]:
df_clean["Quartier"] = df_clean["Quartier"].str.strip()
df_clean["Parking"] = df_clean["Parking"].str.strip()

In [ ]:
df_clean["Quartier"] = df_clean["Quartier"].replace("Quartier","QG")

In [ ]:
print(df_clean["Quartier"].value_counts(dropna=False))
print("\nd",df_clean["Parking"].value_counts(dropna=False))

Quartier
Résidentiel    334
Périphérie     223
Centre         177
Côtier         116
Name: count, dtype: int64

d Parking
Oui    458
Non    392
Name: count, dtype: int64

In [ ]:
n_duplicates = df_clean.duplicated().sum()
print("Nombre de doublons exact:",n_duplicates)

Nombre de doublons exact: 0

In [ ]:
df_clean = df_clean.drop_duplicates().copy()
print("Dimensions apres supression des doublons exacts",df_clean.shape)

Dimensions apres supression des doublons exacts (850, 12)